/**
 * Real portfolio projects — the single source of truth until the DB/admin
 * takes over. Every fact here is verifiable from the CV or the actual
 * design files in "my portfolio/" (git-ignored originals); compressed
 * copies live in /public/images/projects (see scripts/import-portfolio.mjs).
 *
 * CV-truth rule: no invented clients, outcomes, or tools.
 */
import imagesManifest from "./project-images.json";

type ManifestImage = {
  url: string;
  width: number;
  height: number;
  blurDataUrl: string;
};

const images = imagesManifest as Record<string, ManifestImage[]>;

function mediaFor(slug: string, altEn: string, altAr: string) {
  return (images[slug] ?? []).map((img, i) => ({
    id: `${slug}-m${i + 1}`,
    url: img.url,
    type: "IMAGE" as const,
    altEn: `${altEn} — ${i + 1}`,
    altAr: `${altAr} — ${i + 1}`,
    order: i,
    width: img.width,
    height: img.height,
    projectId: slug,
    createdAt: new Date("2026-07-01"),
  }));
}

function coverOf(slug: string) {
  const cover = images[slug]?.[0];
  return {
    coverImage: cover?.url ?? "/images/placeholder.jpg",
    blurDataUrl: cover?.blurDataUrl ?? null,
  };
}

/* ── UI/UX — Web (from "my portfolio/UIUX-web"; covers are studio browser
      mockups generated by scripts/make-mockups.mjs — screens untouched) ── */
const uiuxWebProjects = [
  {
    id: "jadarat",
    slug: "jadarat-platform",
    titleEn: "Jadarat — Consulting & Training Website",
    titleAr: "جدارات — موقع الاستشارات والتدريب",
    descEn:
      "Full website design for Jadarat, a Lattakia-based consulting and training firm: performance analysis and institutional assessment, administrative systems development, and internationally accredited ISO certification services. A warm gold-on-brown Arabic RTL identity across a 30+ page system — home, services, training, careers, and articles.",
    descAr:
      "تصميم موقع متكامل لشركة جدارات للاستشارات والتدريب في اللاذقية: تحليل الأداء والتقييم المؤسسي، تطوير الأنظمة الإدارية والتشغيلية، وشهادات آيزو معتمدة دوليًا. هوية عربية RTL دافئة بذهبي على بني عبر نظام يتجاوز 30 صفحة — الرئيسية، الخدمات، التدريب، الوظائف، والمقالات.",
    category: "UIUX" as const,
    tags: ["Web Design", "RTL", "Corporate"],
    client: "Jadarat",
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2025-06-01"),
  },
  {
    id: "saab",
    slug: "saab-logistics",
    titleEn: "SAAB Logistics — Shipping & Freight Website",
    titleAr: "SAAB Logistics — موقع الشحن والتخليص",
    descEn:
      "Website design for SAAB Logistics, a shipping and logistics company at Lattakia Port: nine pages covering freight services, customs clearance, inland transportation, project cargo, and consulting — with a WhatsApp-first contact flow and a confident blue industrial identity.",
    descAr:
      "تصميم موقع شركة SAAB Logistics للشحن واللوجستيات في مرفأ اللاذقية: تسع صفحات تغطي خدمات الشحن، التخليص الجمركي، النقل الداخلي، البضائع الخاصة، والاستشارات — مع مسار تواصل عبر واتساب وهوية زرقاء صناعية واثقة.",
    category: "UIUX" as const,
    tags: ["Web Design", "Logistics", "Corporate"],
    client: "SAAB Logistics",
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2025-04-01"),
  },
  {
    id: "turki",
    slug: "turki-butchery",
    titleEn: "Turki — Fresh Meat E-Commerce",
    titleAr: "تركي للذبائح — متجر اللحوم الطازجة",
    descEn:
      "E-commerce design for a Saudi online butcher: shop fresh meat by category (whole and by-kilo cuts, ready-to-cook boxes, poultry, sacrificial animals), custom cutting on request, donation baskets, and home delivery — a full Arabic RTL purchase journey across 28 screens.",
    descAr:
      "تصميم متجر إلكتروني سعودي للحوم الطازجة: تسوّق حسب الفئة (لحوم كاملة وبالكيلو، بوكسات جاهزة للطهي، دواجن، أضاحٍ)، تقطيع حسب الطلب، سلة تبرعات، وتوصيل للمنزل — رحلة شراء عربية RTL كاملة عبر 28 شاشة.",
    category: "UIUX" as const,
    tags: ["E-Commerce", "RTL", "Web Design"],
    client: null,
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2025-02-01"),
  },
  {
    id: "kafoo",
    slug: "kafoo-web",
    titleEn: "Kafoo — Investment Company Website",
    titleAr: "كفو — موقع شركة الاستثمار",
    descEn:
      "Website design for Kafoo Investment — guaranteed investment opportunities in used car spare parts. A clean bilingual (Arabic/English) landing covering the company's principle, features, opportunities, and guarantees, in a fresh green identity.",
    descAr:
      "تصميم موقع شركة كفو للاستثمار — فرص استثمارية في قطع غيار السيارات المستعملة. صفحة ثنائية اللغة (عربي/إنجليزي) نظيفة تغطي مبدأ العمل، الميزات، فرص الاستثمار، والضمانات، بهوية خضراء منعشة.",
    category: "UIUX" as const,
    tags: ["Web Design", "Landing", "Bilingual"],
    client: "Kafoo",
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2024-12-01"),
  },
  {
    id: "menu-web",
    slug: "menu-web",
    titleEn: "Digital Restaurant Menu — White-Label Product",
    titleAr: "منيو رقمي للمطاعم — منتج White-Label",
    descEn:
      "Product design for a white-label digital restaurant menu: multi-language, multi-currency, and multi-branch switching, category browsing, offer items, and share flows — built as a reusable template any restaurant can brand.",
    descAr:
      "تصميم منتج منيو رقمي للمطاعم بصيغة White-Label: تعدد لغات وعملات وفروع، تصفح بالفئات، أصناف بعروض، ومشاركة مباشرة — مبني كقالب قابل لإعادة الاستخدام تتبنّاه أي علامة مطعم.",
    category: "UIUX" as const,
    tags: ["Product Design", "SaaS", "Web App"],
    client: null,
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2024-10-01"),
  },
  {
    id: "bigboss",
    slug: "bigboss-web",
    titleEn: "BigBoss — Multi-Category Marketplace",
    titleAr: "BigBoss — متجر متعدد الفئات",
    descEn:
      "E-commerce design for BigBoss, a multi-category marketplace (electronics, fashion, home & living, beauty, sports, toys): promotional hero carousels, top-category rails, special offers, wishlist and cart flows.",
    descAr:
      "تصميم متجر BigBoss متعدد الفئات (إلكترونيات، أزياء، منزل، عناية، رياضة، ألعاب): بانرات عروض متحركة، أقسام رئيسية سريعة الوصول، عروض خاصة، ومسارات مفضلة وسلة شراء.",
    category: "UIUX" as const,
    tags: ["E-Commerce", "Marketplace", "Web Design"],
    client: "BigBoss",
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2024-08-01"),
  },
  {
    id: "phoenitech",
    slug: "phoenitech-website",
    titleEn: "PhoeniTech — Tech Company Website",
    titleAr: "فونيتيك — موقع شركة تقنية",
    descEn:
      "Website design for PhoeniTech, a Syrian technology company positioned as 'your partner to success': integrated solutions covering app development, tech consulting, server management, UI/UX design, and brand building — bilingual Arabic/English with a teal phoenix identity.",
    descAr:
      "تصميم موقع شركة فونيتيك التقنية السورية — «شريكك للنجاح»: حلول متكاملة تشمل تطوير التطبيقات، الاستشارات التقنية، إدارة الخوادم، تصميم الواجهات وتجارب المستخدم، وبناء العلامات التجارية — ثنائي اللغة بهوية العنقاء التركوازية.",
    category: "UIUX" as const,
    tags: ["Web Design", "Bilingual", "Corporate"],
    client: "PhoeniTech",
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2025-05-01"),
  },
  {
    id: "emirates-sands",
    slug: "emirates-sands",
    titleEn: "Emirates Sands — IT Hardware Store",
    titleAr: "Emirates Sands — متجر تقنية",
    descEn:
      "E-commerce design for Emirates Sands Technology (Dubai): laptops, desktops, printers and enterprise hardware with deal zones, faceted category filtering, rich product-spec pages, and a solutions layer (cloud, MPS, IT orchestration).",
    descAr:
      "تصميم متجر Emirates Sands Technology في دبي: لابتوبات وأجهزة مكتبية وطابعات وعتاد مؤسسات، مع منطقة عروض، فلاتر تصنيف متقدمة، صفحات مواصفات غنية، وطبقة خدمات (سحابة، طباعة مُدارة، أتمتة تقنية).",
    category: "UIUX" as const,
    tags: ["E-Commerce", "Hardware", "Web Design"],
    client: "Emirates Sands Technology",
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2025-01-15"),
  },
  {
    id: "codxeon",
    slug: "codxeon-website",
    titleEn: "Codxeon — Digital Agency Website",
    titleAr: "Codxeon — موقع وكالة رقمية",
    descEn:
      "Website design for Codxeon, a digital agency 'transforming ideas into digital excellence': services (web, mobile apps, UI/UX, digital marketing, consultancy), a 24-hour process story, and data-driven strategy sections in a purple-gradient identity.",
    descAr:
      "تصميم موقع وكالة Codxeon الرقمية — «تحويل الأفكار إلى تميز رقمي»: الخدمات (ويب، تطبيقات، UI/UX، تسويق رقمي، استشارات)، قصة عملية تبدأ خلال 24 ساعة، وأقسام استراتيجية قائمة على البيانات بهوية بنفسجية متدرجة.",
    category: "UIUX" as const,
    tags: ["Web Design", "Agency", "Landing"],
    client: "Codxeon",
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2024-06-01"),
  },
  {
    id: "krsy",
    slug: "krsy-web",
    titleEn: "KRSY — Social Media Services Website",
    titleAr: "KRSY — موقع خدمات السوشال ميديا",
    descEn:
      "Website design for KRSY, a social-media growth service for the Middle East: service request flows by platform and category, PayPal checkout steps, and 24/7 support — in a dark neon identity with vivid gradients.",
    descAr:
      "تصميم موقع KRSY لخدمات نمو السوشال ميديا في الشرق الأوسط: مسارات طلب الخدمة حسب المنصة والفئة، خطوات دفع عبر PayPal، ودعم على مدار الساعة — بهوية داكنة نيون بتدرجات حيوية.",
    category: "UIUX" as const,
    tags: ["Web Design", "Dark UI", "Services"],
    client: "KRSY",
    role: "UI/UX Designer",
    tools: [],
    year: null,
    publishedAt: new Date("2024-04-01"),
  },
].map((p) => ({
  ...p,
  bodyEn: null,
  bodyAr: null,
  ...coverOf(p.slug),
  likeCount: 0,
  featured: false,
  published: true,
  createdAt: p.publishedAt,
  updatedAt: new Date("2026-07-12"),
  media: mediaFor(p.slug, `${p.titleEn} — mockup`, `${p.titleAr} — موكاب`),
  likes: [] as never[],
}));

export const projects = [
  ...uiuxWebProjects,
  {
    id: "zanqa",
    slug: "zanqa-education-platform",
    titleEn: "Zanqa Education Platform",
    titleAr: "منصة زنقة التعليمية",
    descEn:
      "An educational platform serving web and mobile audiences in Syria. As Partner & Front-End Developer (2019–2023) I designed the web and mobile UI and built the front-end with Next.js and MUI, while contributing to the product's strategic decisions. The platform reached 94,000+ users and 50,000+ app downloads, working with 3,000+ publishers.",
    descAr:
      "منصة تعليمية تخدم جمهورها عبر الويب والموبايل في سوريا. عملت عليها كشريكة ومطوّرة واجهات أمامية (2019–2023): صمّمت واجهات الويب والموبايل وبنيت الواجهة الأمامية باستخدام Next.js وMUI، وشاركت في القرارات الاستراتيجية للمنتج. وصلت المنصة إلى أكثر من 94,000 مستخدم و50,000 تحميل للتطبيق، بالعمل مع أكثر من 3,000 ناشر.",
    bodyEn: null,
    bodyAr: null,
    category: "WEBSITES" as const,
    tags: ["Education", "Mobile App", "Web Platform"],
    ...coverOf("zanqa-education-platform"),
    client: "Zanqa",
    role: "Partner & Front-End Developer",
    tools: ["Next.js", "MUI", "Adobe XD"],
    year: 2023,
    likeCount: 0,
    featured: true,
    published: true,
    publishedAt: new Date("2023-01-15"),
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2026-07-10"),
    media: mediaFor(
      "zanqa-education-platform",
      "Zanqa app screens",
      "شاشات تطبيق زنقة"
    ),
    likes: [],
  },
  {
    id: "e-liefer",
    slug: "e-liefer-delivery-platform",
    titleEn: "E-Liefer — Delivery Platform UX/UI",
    titleAr: "E-Liefer — تصميم منصة توصيل",
    descEn:
      "Complete UX/UI design for a German-market delivery platform connecting local stores to customers: shop from any store and get it delivered home. I designed the full journey in Adobe XD — onboarding and registration, store discovery by district, product browsing and details, favorites, and store profiles — in English and German.",
    descAr:
      "تصميم UX/UI كامل لمنصة توصيل موجهة للسوق الألماني تربط المتاجر المحلية بالعملاء: تسوّق من أي متجر ويصلك الطلب إلى المنزل. صمّمت الرحلة كاملة في Adobe XD — التسجيل، استكشاف المتاجر حسب المنطقة، تصفح المنتجات وتفاصيلها، المفضلة، وملفات المتاجر — باللغتين الإنجليزية والألمانية.",
    bodyEn: null,
    bodyAr: null,
    category: "UIUX" as const,
    tags: ["Web App", "Delivery", "UX Flow"],
    ...coverOf("e-liefer-delivery-platform"),
    client: "E-Liefer",
    role: "UI/UX Designer",
    tools: ["Adobe XD"],
    year: 2021,
    likeCount: 0,
    featured: true,
    published: true,
    publishedAt: new Date("2021-10-23"),
    createdAt: new Date("2021-10-23"),
    updatedAt: new Date("2026-07-10"),
    media: mediaFor(
      "e-liefer-delivery-platform",
      "E-Liefer platform screens",
      "شاشات منصة E-Liefer"
    ),
    likes: [],
  },
  {
    id: "living-app",
    slug: "living-app-ui",
    titleEn: "Living — Housing Management App",
    titleAr: "Living — تطبيق إدارة سكنية",
    descEn:
      "UI/UX design for a housing-management mobile app: residents manage their home, connect with neighbors, and stay informed in one place. Screens cover property details (unit info, floor plans), service and repair requests, move-in/move-out logistics, issue reporting, and community announcements.",
    descAr:
      "تصميم UI/UX لتطبيق موبايل لإدارة السكن: يتيح للسكان إدارة منازلهم والتواصل مع الجيران ومتابعة المستجدات في مكان واحد. تغطي الشاشات تفاصيل العقار (معلومات الوحدة والمخططات)، طلبات الصيانة والإصلاح، إجراءات الانتقال، الإبلاغ عن المشكلات، وإعلانات المجتمع السكني.",
    bodyEn: null,
    bodyAr: null,
    category: "UIUX" as const,
    tags: ["Mobile App", "Property", "UI Design"],
    ...coverOf("living-app-ui"),
    client: null,
    role: "UI/UX Designer",
    tools: ["Figma"],
    year: null,
    likeCount: 0,
    featured: false,
    published: true,
    publishedAt: new Date("2024-01-01"),
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2026-07-10"),
    media: mediaFor("living-app-ui", "Living app screens", "شاشات تطبيق Living"),
    likes: [],
  },
  {
    id: "nana-gelato",
    slug: "nana-gelato-packaging",
    titleEn: "Nana — Gelato Packaging Series",
    titleAr: "نعناع — سلسلة عبوات جيلاتو",
    descEn:
      "Product packaging design for “nana | نعناع” Italian gelato: a flavor series (strawberry, mango, and more) with a bilingual Arabic/English label system. One visual system carries the brand across the series while each flavor keeps its own appetizing identity.",
    descAr:
      "تصميم عبوات منتجات لجيلاتو إيطالي بعلامة «نعناع nana»: سلسلة نكهات (فريز، مانجو، وغيرها) بنظام ملصقات ثنائي اللغة عربي/إنجليزي. نظام بصري واحد يحمل هوية العلامة عبر السلسلة، مع شخصية شهيّة مستقلة لكل نكهة.",
    bodyEn: null,
    bodyAr: null,
    category: "GRAPHIC_DESIGN" as const,
    tags: ["Packaging", "Branding", "FMCG"],
    ...coverOf("nana-gelato-packaging"),
    client: "nana | نعناع",
    role: "Graphic Designer",
    tools: ["Photoshop", "Illustrator"],
    year: null,
    likeCount: 0,
    featured: true,
    published: true,
    publishedAt: new Date("2022-06-01"),
    createdAt: new Date("2022-06-01"),
    updatedAt: new Date("2026-07-10"),
    media: mediaFor(
      "nana-gelato-packaging",
      "Nana gelato packaging",
      "عبوات جيلاتو نعناع"
    ),
    likes: [],
  },
  {
    id: "believe-in-syria",
    slug: "believe-in-syria-campaign",
    titleEn: "Believe in Syria — Campaign Identity",
    titleAr: "Believe in Syria — هوية الحملة",
    descEn:
      "Campaign identity and media collateral for JCI Syria's “Believe in Syria” campaign, where I served as Media Director (2018–2019): campaign one-pagers, formal invitations, table cards, business cards, T-shirts, and the campaign book — leading print and digital media production for large-scale outreach.",
    descAr:
      "الهوية البصرية والمواد الإعلامية لحملة «Believe in Syria» التابعة لـ JCI سوريا، حيث عملت مديرةً إعلامية (2018–2019): ملفات تعريفية، دعوات رسمية، بطاقات طاولات وبطاقات شخصية، تيشيرتات، وكتيّب الحملة — مع قيادة الإنتاج الإعلامي المطبوع والرقمي لحملة تواصل واسعة النطاق.",
    bodyEn: null,
    bodyAr: null,
    category: "GRAPHIC_DESIGN" as const,
    tags: ["Campaign", "Branding", "Print"],
    ...coverOf("believe-in-syria-campaign"),
    client: "JCI Syria",
    role: "Media Director",
    tools: ["Photoshop", "Illustrator"],
    year: 2018,
    likeCount: 0,
    featured: true,
    published: true,
    publishedAt: new Date("2018-10-01"),
    createdAt: new Date("2018-10-01"),
    updatedAt: new Date("2026-07-10"),
    media: mediaFor(
      "believe-in-syria-campaign",
      "Believe in Syria campaign collateral",
      "مواد حملة Believe in Syria"
    ),
    likes: [],
  },
  {
    id: "travel-agency",
    slug: "travel-agency-branding",
    titleEn: "Travel Agency — Brand & Collateral",
    titleAr: "وكالة سفر — هوية ومطبوعات",
    descEn:
      "Brand identity and print collateral for a travel agency: logo showcase, ID cards, brochure covers (front and back), social cover, and interior page layouts.",
    descAr:
      "هوية بصرية ومطبوعات لوكالة سفر: عرض الشعار، بطاقات تعريفية، أغلفة بروشور (أمامي وخلفي)، غلاف سوشال ميديا، وتنسيقات الصفحات الداخلية.",
    bodyEn: null,
    bodyAr: null,
    category: "GRAPHIC_DESIGN" as const,
    tags: ["Branding", "Print", "Logo"],
    ...coverOf("travel-agency-branding"),
    client: null,
    role: "Graphic Designer",
    tools: ["Photoshop", "Illustrator"],
    year: null,
    likeCount: 0,
    featured: false,
    published: true,
    publishedAt: new Date("2020-05-01"),
    createdAt: new Date("2020-05-01"),
    updatedAt: new Date("2026-07-10"),
    media: mediaFor(
      "travel-agency-branding",
      "Travel agency branding",
      "هوية وكالة السفر"
    ),
    likes: [],
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug) ?? null;
}
